Repository CLDXiang/huiyou.js, pull requests merged in 2020-10, with the labels that each got.

#3 feat(api): introduce test api in app
  .env
  .eslintrc.js
  src/apis/index.ts
  src/apis/test.ts
  src/app/App.vue
  src/utils/config.ts
  vue.config.js
Labels: enhancement

#6 feat:push records
  .env
  babel.config.js
  package.json
  src/apis/index.ts
  src/apis/record.ts
  src/apis/test.ts
  src/app/App.vue
  src/app/components/HelloWorld.vue
  src/app/components/PushRecordItem.vue
  src/app/views/PushRecords.vue
  src/main.ts
  vue.config.js
  yarn.lock
Labels: enhancement, 单页应用

#5 初步完成后端脚本逻辑
  src/apis/test.ts
  src/background/backend.ts
  src/background/config.ts
  src/background/fetchVideo.ts
  src/background/main.ts
  src/background/messageCallback.ts
  src/background/recordVideo.ts
  src/background/timekeeping.ts
  src/background/webRequestListener/index.ts
  src/background/webRequestListener/requestHandler.ts
  src/background/webRequestListener/requestTypeCheck.ts
  src/types/message.ts
  src/types/video.ts
  src/types/webRequest.ts
  src/utils/message.ts
  src/utils/parsePath.ts
  vue.config.js
Labels: enhancement, 背景脚本

#8 修复单页应用中图片不显示的问题
  src/apis/record.ts
  src/apis/test.ts
  vue.config.js
Labels: bug, 单页应用
