Repository CLDXiang/huiyou.js, pull requests merged in 2020-11, with the labels that each got.

#12 Feature background
  .eslintrc.js
  src/apis/index.ts
  src/apis/records.ts
  src/apis/utils.ts
  src/apis/videos.ts
  src/background/backend.ts
  src/background/fetchVideo.ts
  src/background/messageCallback.ts
  src/background/recordVideo.ts
  src/background/timekeeping.ts
  src/config/backend.ts
  src/config/frontend.ts
  src/config/index.ts
  src/types/backendRequest.ts
  src/types/message.ts
  src/types/video.ts
  src/types/webRequest.ts
Labels: 背景脚本

#14 移除 Antd（顺便引入 B 站 API）
  .vscode/settings.json
  babel.config.js
  package.json
  src/apis/bilibili.ts
  src/apis/index.ts
  src/apis/record.ts
  src/apis/records.ts
  src/apis/utils.ts
  src/apis/videos.ts
  src/app/apis/bilibili.ts
  src/app/apis/index.ts
  src/app/apis/records.ts
  src/app/components/PushRecordItem.vue
  src/app/types.ts
  src/app/views/PushRecords.vue
  src/config/frontend.ts
  src/main.ts
  src/types/backendRequest.ts
  src/types/biliRequest.ts
  src/utils/parseUrl.ts
  yarn.lock
Labels: enhancement, 单页应用

#13 Feature background
  .vscode/settings.json
  src/apis/bilibili.ts
  src/apis/utils.ts
  src/app/apis/bilibili.ts
  src/background/fetchVideo.ts
  src/background/recordVideo.ts
  src/background/webRequestListener/requestTypeCheck.ts
  src/config/bilibiliApi.ts
  src/config/frontend.ts
  src/config/index.ts
  src/types/bilibiliApiRequest.ts
  src/types/message.ts
  src/types/video.ts
  src/types/webRequest.ts
  src/utils/parseUrl.ts
  src/utils/url.ts
Labels: 背景脚本

#7 content script：popup窗口基础功能实现
  .env.debug
  package.json
  public/img/guanbi-1.svg
  public/img/guanbi-2.svg
  public/img/tag-browser.png
  public/img/tag.png
  public/manifest.json
  src/apis/bilibili.ts
  src/background/backend.ts
  src/config/backend.ts
  src/config/bilibiliApi.ts
  src/config/frontend.ts
  src/popup/apis/bilibili.ts
  src/popup/apis/index.ts
  src/popup/guanbi-1.svg
  src/popup/guanbi-2.svg
  src/popup/main.ts
  src/popup/popup.less
  src/popup/showVideo.ts
  src/popup/timeKeeper.ts
  src/popup/videoShot.ts
  src/types/bilibiliApiRequest.ts
  src/types/video.ts
  src/utils/config.ts
Labels: 页面脚本

#19 视频播放进度监测
  .vscode/settings.json
  src/background/backend.ts
  src/config/frontend.ts
  src/popup/main.ts
  src/popup/showVideo.ts
  src/popup/videoProgress.ts
  src/utils/logger.ts
Labels: 页面脚本

#20 build(webpack): 独立各模块打包时的模块依赖
  public/manifest.json
  vue.config.js
Labels: 单页应用, 背景脚本, 页面脚本

#21 Feat popup
  package.json
  src/background/api.ts
  src/background/messageCallback.ts
  src/config/frontend.ts
  src/popup/main.ts
  yarn.lock
Labels: 背景脚本, 页面脚本

#22 Feature network
  src/apis/records.ts
  src/apis/videos.ts
  src/background/api.ts
  src/background/backend.ts
  src/background/webRequestListener/requestHandler.ts
Labels: 背景脚本

#23 build: 内联引入 svg
  package.json
  src/popup/showVideo.ts
  src/types.d.ts
  vue.config.js
  yarn.lock
Labels: enhancement, 页面脚本
