Repository CLDXiang/huiyou.js, pull requests merged in 2020-12, with the labels that each got.

#25 用插件 API 获取 cookie
  public/manifest.json
  src/background/api.ts
  src/background/messageCallback.ts
  src/background/recordVideo.ts
  src/background/webRequestListener/requestTypeCheck.ts
  src/config/bilibiliApi.ts
  src/popup/main.ts
  src/types/message.ts
  src/utils/cookies.ts
Labels: enhancement, 单页应用, 背景脚本, 页面脚本

#26 build(webpack): 新增 dev 脚本，支持自动重新编译
  package.json
Labels: enhancement

#27 feat:获取uid&UI优化
  src/app/components/PushRecordItem.vue
  src/app/views/PushRecords.vue
  src/assets/icons.png
Labels: 单页应用

#30 fix(popup): 视频进度监测兼容分 p 情况
  src/popup/main.ts
  src/popup/videoProgress.ts
  src/utils/url.ts
Labels: bug, 页面脚本

#32 新增 fetchVideoForcedly 消息接口
  src/background/fetchVideo.ts
  src/background/messageCallback.ts
  src/background/recordVideo.ts
  src/types/message.ts
Labels: enhancement, 背景脚本

#29 fix(pop-up): 改了计时器的bug
  .gitattributes
  public/img/simple-tag-hover.gif
  public/img/simple-tag.png
  src/assets/simple-tag-hover.gif
  src/assets/simple-tag.png
  src/background/timekeeping.ts
  src/popup/main.ts
  src/popup/popup.less
  src/popup/showVideo.ts
  src/popup/timeKeeper.ts
  src/types.d.ts
  src/utils/timeKeeper.ts
  vue.config.js
Labels: bug, 页面脚本

#34 feat: 修改后端接口
  src/background/api.ts
  src/types/backendRequest.ts
Labels: enhancement, 背景脚本

#36 重构 Popup
  .eslintrc.js
  .vscode/settings.json
  package.json
  public/img/guanbi-1.svg
  public/img/guanbi-2.svg
  public/img/simple-tag-hover.gif
  public/img/simple-tag.png
  src/assets/close.svg
  src/background/messageCallback.ts
  src/background/timekeeping.ts
  src/popup/apis/bilibili.ts
  src/popup/bubble.ts
  src/popup/main.ts
  src/popup/popup.less
  src/popup/popup.ts
  src/popup/showVideo.ts
  src/popup/timeKeeper.ts
  src/popup/utils.ts
  src/popup/videoProgress.ts
  src/popup/videoShot.ts
  src/types/message.ts
  src/types/video.ts
  src/utils/logger.ts
  src/utils/message.ts
  src/utils/url.ts
  yarn.lock
Labels: 背景脚本, 页面脚本

#37 feat(popup): 弹窗显隐增加渐变效果
  src/popup/popup.less
Labels: 页面脚本

#40 feat: 增加视频缓存
  src/background/videoCandidate.ts
  src/config/frontend.ts
Labels: enhancement, 背景脚本

#41 Refactor background
  src/background/messageCallback.ts
  src/background/recordVideo.ts
  src/background/timekeeping.ts
  src/background/videoCandidate.ts
Labels: enhancement, 背景脚本

#42 fix(app): add alt to img
  src/app/App.vue
  src/app/components/Empty.vue
  src/app/components/HonorItem.vue
  src/app/components/PushRecordItem.vue
  src/options/views/PushRecords.vue
Labels: bug, 单页应用

#44 配置项数据逻辑
  src/background/fetchVideo.ts
  src/background/recordVideo.ts
  src/config/frontend.ts
  src/popup/main.ts
  src/utils/options.ts
Labels: enhancement, 自定义选项

#45 自定义选项页
  src/app/App.vue
  src/background/recordVideo.ts
  src/config/frontend.ts
  src/options/Options.vue
  src/options/components/Checkbox.vue
  src/options/components/Tooltip.vue
  src/options/components/UpDownPin.vue
  src/options/components/index.ts
  src/options/utils/index.ts
  src/options/utils/parse.ts
  src/options/utils/storage.ts
  src/popup/main.ts
  src/popup/popup.ts
  src/utils/options.ts
  src/utils/parsePath.ts
Labels: enhancement, 自定义选项

#47 Refactor icons
  src/app/App.vue
  src/app/components/PushRecordItem.vue
  src/assets/icons.png
  src/assets/lishi.png
  src/assets/lishi2.png
  src/assets/rongyubiaozhang.png
  src/assets/rongyubiaozhang2.png
Labels: enhancement, 单页应用

#46 feat(popup): 弹窗显示播放量和 up 主
  src/app/components/PushRecordItem.vue
  src/popup/popup.less
  src/popup/popup.ts
  src/utils/videoInfo.ts
Labels: enhancement, 页面脚本

#49 fix: 爬取视频时排除已缓存的视频
  src/background/fetchVideo.ts
  src/background/videoCandidate.ts
Labels: bug, 背景脚本

#50 fix(popup): 点击浮窗跳转后关闭浮窗
  src/popup/popup.ts
Labels: bug, 页面脚本

#52 图片通过 url 引入
  public/img/close.svg
  public/img/coin.svg
  public/img/empty.png
  public/img/favorite.svg
  public/img/history-img.jpg
  public/img/honor-time.png
  public/img/honor-up.png
  public/img/honor-zuji.png
  public/img/like.svg
  public/img/simple-tag-hover.gif
  public/img/simple-tag.png
  public/img/view.svg
  public/manifest.json
  src/app/App.vue
  src/app/components/Empty.vue
  src/app/components/HonorItem.vue
  src/app/components/PushRecordItem.vue
  src/popup/bubble.ts
  src/popup/popup.ts
  src/types.d.ts
  vue.config.js
Labels: enhancement, 单页应用, 页面脚本
